//20160302
var g_sLang = "en";
var g_sDefaultSpan = '<span style="font-family:robotoregular,arial,helvetica,sans-serif;font-size:16px;color:#000000;">​&nbsp;</span>';
var g_oStrings =
{
	"action": "Action",
	"switch_bg": "Toggle background color"
};
var g_aSpecialChars = [
	[ "&nbsp;", "Non-breaking space" ],
	[ "&quot;", "Quotation mark" ],
	[ "&laquo;", "Left double quotation mark" ],
	[ "&raquo;", "Right double quotation mark" ],
	[ "&acute;", "Spacing acute" ],
	[ "&ndash;", "En dash" ],
	[ "&mdash;", "Em dash" ],
	[ "&iexcl;", "Inverted exclamation mark" ],
	[ "&iquest;", "Inverted question mark" ],
	[ "&sect;", "Section sign" ],
	[ "&copy;", "Copyright sign" ],
	[ "&reg;", "Registered sign" ],
	[ "&trade;", "Trade mark sign" ],
	[ "&dagger;", "Dagger" ],
	[ "&Dagger;", "Double dagger" ],
	[ "&bull;", "Bullet" ],
	[ "&larr;", "Left arrow" ],
	[ "&rarr;", "Right arrow" ],
	[ "&uarr;", "Up arrow" ],
	[ "&darr;", "Down arrow" ],
	[ "&harr;", "Left right arrow" ],
	[ "&crarr;", "Carriage return arrow" ],
	[ "&lArr;", "Left double arrow" ],
	[ "&rArr;", "Right double arrow" ],
	[ "&uArr;", "Up double arrow" ],
	[ "&dArr;", "Down double arrow" ],
	[ "&hArr;", "Left right double arrow" ],
	[ "&deg;", "Degree sign" ],
	[ "&permil;", "Per mille" ],
	[ "&plusmn;", "Plus or minus" ],
	[ "&frac14;", "Vulgar fraction one quarter" ],
	[ "&frac12;", "Vulgar fraction one half" ],
	[ "&frac34;", "Vulgar fraction three quarters" ],
	[ "&times;", "Multiplication sign" ],
	[ "&divide;", "Division sign" ],
	[ "&nabla;", "Nabla" ],
	[ "&prod;", "Product" ],
	[ "&sum;", "Sum" ],
	[ "&minus;", "Minus" ],
	[ "&radic;", "Square root" ],
	[ "&int;", "Integral" ],
	[ "&part;", "Part" ],
	[ "&asymp;", "Almost equal to" ],
	[ "&ne;", "Not equal" ],
	[ "&equiv;", "Equivalent" ],
	[ "&le;", "Less or equal" ],
	[ "&ge;", "Greater or equal" ],
	[ "&infin;", "Infinity" ],
	[ "&ang;", "Angle" ],
	[ "&forall;", "For all" ],
	[ "&exist;", "Exist" ],
	[ "&there4;", "Therefore" ],
	[ "&empty;", "Empty" ],
	[ "&isin;", "Is in" ],
	[ "&notin;", "Not in" ],
	[ "&ni;", "Ni" ],
	[ "&prop;", "Proportional to" ],
	[ "&cap;", "Cap" ],
	[ "&cup;", "Cup" ],
	[ "&sub;", "Subset of" ],
	[ "&sup;", "Superset of" ],
	[ "&nsub;", "Not subset of" ],
	[ "&sube;", "Subset or equal" ],
	[ "&supe;", "Superset or equal" ],
	[ "&Alpha;", "Alpha" ],
	[ "&alpha;", "alpha" ],
	[ "&Beta;", "Beta" ],
	[ "&beta;", "beta" ],
	[ "&Gamma;", "Gamma" ],
	[ "&gamma;", "gamma" ],
	[ "&Delta;", "Delta" ],
	[ "&delta;", "delta" ],
	[ "&Epsilon;", "Epsilon" ],
	[ "&epsilon;", "epsilon" ],
	[ "&Zeta;", "Zeta" ],
	[ "&zeta;", "zeta" ],
	[ "&Eta;", "Eta" ],
	[ "&eta;", "eta" ],
	[ "&Theta;", "Theta" ],
	[ "&theta;", "theta" ],
	[ "&Iota;", "Iota" ],
	[ "&iota;", "iota" ],
	[ "&Kappa;", "Kappa" ],
	[ "&kappa;", "kappa" ],
	[ "&Lambda;", "Lambda" ],
	[ "&lambda;", "lambda" ],
	[ "&Mu;", "Mu" ],
	[ "&mu;", "mu" ],
	[ "&Nu;", "Nu" ],
	[ "&nu;", "nu" ],
	[ "&Xi;", "Xi" ],
	[ "&xi;", "xi" ],
	[ "&Omicron;", "Omicron" ],
	[ "&omicron;", "omicron" ],
	[ "&Pi;", "Pi" ],
	[ "&pi;", "pi" ],
	[ "&Rho;", "Rho" ],
	[ "&rho;", "rho" ],
	[ "&Sigma;", "Sigma" ],
	[ "&sigma;", "sigma" ],
	[ "&Tau;", "Tau" ],
	[ "&tau;", "tau" ],
	[ "&Upsilon;", "Upsilon" ],
	[ "&upsilon;", "upsilon" ],
	[ "&Phi;", "Phi" ],
	[ "&phi;", "phi" ],
	[ "&Chi;", "Chi" ],
	[ "&chi;", "chi" ],
	[ "&Psi;", "Psi" ],
	[ "&psi;", "psi" ],
	[ "&Omega;", "Omega" ],
	[ "&omega;", "omega" ],
	[ "&micro;", "Micro" ],
	[ "&thetasym;", "Theta symbol" ],
	[ "&upsih;", "Upsilon symbol" ],
	[ "&piv;", "Pi symbol" ]
];